bookthird/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import debug_toolbar
from orders.views import admin_order_detail, get_pdf_admin
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _


urlpatterns = i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path('admin/orders/custom/<int:order_id>/', admin_order_detail, name="admin_order_detail"),    # url for custom order detail page
    path('admin/orders/invoice/<int:order_id>/', get_pdf_admin, name='get_pdf_admin'),
    path('rosetta/', include('rosetta.urls')),
    path('', include('cart.urls')),
    path('', include('coupon.urls')),
    path('', include('shop.urls')),
    path(_('order/'), include('payments.urls')),
    path(_('order/'), include('orders.urls')),
    path('__debug__/', include(debug_toolbar.urls)),

)

if settings.DEBUG:
#   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _
urlpatterns = [
    path(_('cart/'), views.cart_detail, name='cart_detail'),
    path('cart/add/<int:product_id>/', views.cart_add, name="add_cart"),
    path('cart/remove/<int:product_id>/', views.cart_remove, name="remove_cart")
]

coupon/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _
app_name = 'coupon'

urlpatterns = [
    path(_('coupons/'), views.apply_coupon, name="apply_coupon"),

]

orders/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _
app_name = 'orders'

urlpatterns = [
    path(_('checkout/'), views.orderMain, name="checkout"),
    path(_('order-success/'), views.orderMain, name="order_success"),
    path('admin/orders/custom/<int:order_id>/', views.admin_order_detail, name="admin_order_detail")

]

shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('<slug:category_slug>/', views.home, name='home_category'),
    path('<int:id>/<slug:product_slug>/', views.product_detail, name='product_detail')
]

cart/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
import os
import datetime
from django.utils import timezone
from django.shortcuts import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        url = reverse('home_category', args=[self.slug])
        return url

    def __str__(self):
        return self.name

def image_location(instance, filename):
    time_now = timezone.now()
    loc = os.path.join('product_images', instance.product.slug, time_now.strftime('%Y'), time_now.strftime('%m'), filename)
    return loc


class Product(models.Model):
    name = models.CharField(max_length=300, db_index=True)
    slug = models.CharField(max_length=100, db_index=True)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    description = models.TextField(max_length=500, null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'))

    def get_absolute_url(self):
        url = reverse('product_detail', args=[self.id, self.slug])
        return url

    def get_single_image(self):
        return self.images.all()[0].image.url

    def __str__(self):
        return self.name

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=image_location, default='img-default.gif')

cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
QUANTITY_CHOISES = [(i, str(i)) for i in range(21)]

class AddQuantityForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=QUANTITY_CHOISES, coerce=int, label=_('Quantity'))
    overide = forms.BooleanField(required=False, widget=forms.HiddenInput, initial=False)

coupon/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
class CouponCodeForm(forms.Form):
    code = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder': "Coupon Code", 'class': 'form-control'}), label=_('Coupon'))

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import AddQuantityForm
from shop.models import Product
from .cart import Cart
from django.views.decorators.http import require_POST
from coupon.forms import CouponCodeForm
from shop.recommander import Recommander

# Create your views here.
# View to add product to cart or update Quantity
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    selected_product = get_object_or_404(Product, id=product_id)
    quantity_form = AddQuantityForm(request.POST)
    if quantity_form.is_valid():
        cd = quantity_form.cleaned_data
        cart.add(selected_product, cd['quantity'], cd['overide'])
    return redirect('cart_detail')

# Cart remove view to remove product from the cart from cart
def cart_remove(request, product_id):
    cart = Cart(request)
    selected_product = get_object_or_404(Product, id=product_id)
    cart.remove(selected_product)
    return redirect('cart_detail')

# Cart Detail View where we can view all items in the cart
def cart_detail(request):
    coupon_form = CouponCodeForm()
    cart = Cart(request)
    cart_products = []
    for item in cart:
        item['quantity_form'] = AddQuantityForm(initial={'quantity': item['quantity'], 'overide': True})
        cart_products.append(item['product'])
    r = Recommander()
    suggested_products = r.suggest_products(cart_products, 3)
    context = {'cart': cart, 'coupon_form': coupon_form, 'suggested_products': suggested_products}
    return render(request, 'cart/cart_detail.html', context)

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import AddQuantityForm
from django.conf import settings
from .recommander import Recommander
# Create your views here.
def home(request, category_slug=None):
    # set category to none bcoz we want to send category to context and we will get error if category_slug is not provided
    # Get all category and product to display on home page 
    category = None
    products = Product.objects.all().prefetch_related('images')
    categories = Category.objects.all()
    if category_slug:
        # id category slug is passed it means that the user has clicked on a category and we want to show product on that specific category 
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
        
    context = {'category': category, 'categories': categories, 'products': products}
    return render(request, 'product/home.html', context)

def product_detail(request, id, product_slug):
    selected_product = get_object_or_404(Product, id=id, slug=product_slug)
    cart_session = request.session.get(settings.CART_SESSION_ID)
    quantity_init = cart_session[str(selected_product.id)]['quantity'] if cart_session.get(str(selected_product.id)) else 0
    quantity_form = AddQuantityForm(initial={'quantity': quantity_init})
    r = Recommander()
    product_suggestions = r.suggest_products([selected_product], max_result=3)
    context = {'selected_product': selected_product, 'add_to_cart': quantity_form, 'product_suggestion': product_suggestions}
    return render(request, 'product/product_details.html', context)

shop/templates/cart/cart_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static '/css/cart-detail.css' %}">
<style>
    .coupon-form {
        display: flex;
    }
</style>
{% endblock %}
{% block title %}
<title>{% trans 'Cart Detail' %}</title>
{% endblock %}
{% block content %}
<section>
    {% with total_items=cart|length %}
 
        <h1>{% translate "You Have" %} 
        {% blocktrans with total=cart.get_cart_total count total_items_trans=total_items %}
            {{total_items_trans}} Item {% plural %} {{total_items_trans}} Items
        {% endblocktrans %}
        </h1>

    {% endwith %}
    <article class="cart-container">
        <table class="table">
            <thead>
              <tr>
                <th>{% trans 'Image' %}</th>
                <th>{% trans 'Product' %}</th>
                <th>{% trans 'Quantity' %}</th>
                <th>{% trans 'Remove' %}</th>
                <th>{% trans 'Unit Price' %}</th>
                <th>{% trans 'Price' %}</th>
              </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                {% if item %}
                    {% with product=item.product %}
                    <tr class="product-item">
                        <td>
                            <a href="{{product.get_absolute_url}}" class="image-link">
                                <img src="{{product.get_single_image}}" width="60" height="60">
                            </a>
                        </td>
                        {% blocktrans with product_name=product.name %}
                        <td>{{product_name}}</td>
                        {% endblocktrans %}
                        <td>
                            <form method="POST" action="{% url 'add_cart' product.id %}">
                                {% csrf_token %}
                                {{item.quantity_form.quantity}}
                                {{item.quantity_form.overide}}
                                <button type="submit" class="btn btn-info btn-sm">{% trans "Update" %}</button>
                            </form>
                        </td>
                        <td>
                            <form class="remove-product" action="{% url 'remove_cart' product.id %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger btn-sm">{% trans "Remove" %}</button>
                            </form>
                        </td>
                        <td>Rs {{item.price}}</td>
                        <td>Rs {{item.total_price}}</td>
                    </tr>
                    {% endwith %}
                {% else %}
                    <tr>
                        <td colspan="6">{% trans "Your Cart is Empty"%}</td>
                    </tr>
                {% endif %}
                {% endfor %}
                    <tr class="cart-total">
                        <td>{% trans "Total" %}</td>
                        <td colspan="4"></td>
                        <td>{{cart.get_cart_total}}</td>
                    </tr>
                    <tr class="cart-discount">
                        <td>{% trans "Discount" %}</td>
                        <td colspan="4"></td>
                        <td class="target">{{cart.get_discount}}</td>
                    </tr>
                    <tr class="cart-total-final">
                        <td>{% trans "Price After Discount" %}</td>
                        <td colspan="4"></td>
                        <td class="target">{{cart.price_after_discount|floatformat:2}}</td>
                    </tr>
            </tbody>
          </table>
        </div>
    </article>
    <article class="coupon-form">
        <form class="coupon-form" method="POST" id="coupon-apply">
            {% csrf_token %}
            {{coupon_form.code}}
            <input type="submit" class="btn btn-success" value="{% translate "Apply" %}"">
            <div class="form-msg"></div>
        </form>
    </article>
    <article class="cart-options">
        <a href="{% url 'home'%}" class="btn btn-info">{% trans 'Continue Shopping' %}</a>
        <a href="{% url 'orders:checkout' %}" class="btn btn-success">{% trans "Checkout" %}</a>
    </article>
    {% if suggested_products %}
    <article class="recommandation">
        <h4>{% translate "People who Bought this Product also Baught" %}</h4>
        <div class="recommandation-list">
            {% for product in suggested_products %}
            <div class="recommandation-item">
                <a href="{{product.get_absolute_url}}" class="recommandation-item-link">
                <img src="{{product.get_single_image}}" class="recommanded-image">
                <p>{{product.name|truncatewords:3}}</p>
                </a>
            </div>
            {% endfor %}
        </div>
    </article>
    {% endif %}
</section>
{% endblock %}
{% block js %}
<script>
$(window).ready(function(){
    $('#coupon-apply').submit(function(e){
        e.preventDefault()
        let coupon_code = $('#id_code').val()
        const url = "{% url 'coupon:apply_coupon' %}"

        $.post(url, {csrfmiddlewaretoken: document.getElementsByName('csrfmiddlewaretoken')[0].value, code: coupon_code}, function(response){
            let total = "{{cart.get_cart_total}}"
            let discount = response['discount']
            let discount_ammount = parseInt(total) * discount / 100
            if (response['status'] === 'ok'){

                $('.cart-discount .target').text(discount_ammount)
                $('.cart-total-final .target').text(parseInt(total) - discount_ammount)
                $('.form-msg').text(response['code'] + '{% trans "Applied" %}')
                console.log(this.children)
            }
            else{
                $('.form-msg').text(response['code'] + ' {% trans "is not a valid Coupon." %}')
                $('.cart-discount .target').text(0)
                $('.cart-total-final .target').text(total)
            }
        })

    })
})
</script>
{% endblock %}